config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts
  resources :conversations do 
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  validates :user_id, presence: true 
  validates :title, presence: true, length: { maximum: 140 }
  validates :description, presence: true
  
  mount_uploader :image, ImageUploader
  
  validate :image_size_validation
  
  private
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  has_many :posts, dependent: :destroy
  acts_as_messageable
  
  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    
    before_action :authenticate_user!
    
    def index
        @conversations = current_user.mailbox.conversations
    end
    
    def new
        @reciever = User.find(params[:reciever_id])
    end
    
    def create
        reciever = User.find(params[:user_id])
        recit = current_user.send_message(reciever, params[:body], params[:subject])
        redirect_to conversation_path(recit.conversation)
    end
    
    def show
        @conversation = current_user.mailbox.conversations.find(params[:id])
        @conversation.mark_as_read(current_user)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    
    before_action :set_conversation
    
    def create
        r = current_user.reply_to_conversation(@conversation, params[:body])
        redirect_to conversation_path(r.conversation) 
    end
    
    private 
        def set_conversation
            @conversation = current_user.mailbox.conversations.find(params[:conversation_id])
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    before_action :authenticate_user!, :except => [:show, :index]
    

    def new
        @post = Post.new
    end
    
    def show
        @post = Post.find(params[:id])
    end
    
    def create
        @post = current_user.posts.build(post_params)
        if @post.save
            flash[:success] = "Hosting created!"
            redirect_to post_path(@post.id)
        else
            # TODO Create a Error Page
            redirect_to '/404.html'
        end
    end
    
    def index
        @posts = Post.all
    end
    
    def destroy
        @post = Post.find(params[:id])
        if @post.user == current_user
            if @post.destroy
                flash[:success] = "Posts Deleted!"
                redirect_to posts_path
            else
                render '/'
            end
        else
            redirect_to root_path
        end
    end
    
    private 
    
    def post_params
        params.require(:post).permit(:title, :description, :image)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/conversations/index.html.erb
</br>
</br>
<div class="row">
    <div class="col-lg-12 text-center">
        <h2>Welcome to your mailbox <%= current_user.name %> !!!</h2>
        <h3>All Conversations Listed Here</h3>
        <hr class="star-primary">
    </div>
    <div class="col-lg-12 text-center"> 
        Inbox (<%= current_user.mailbox.inbox.unread(current_user).count %>) |
        All Conversations (<%= current_user.mailbox.conversations.count %>) |
        Sent (<%= current_user.mailbox.sentbox.count %>) |
        Trash (<%= current_user.mailbox.trash.count %>)     
    </div>
    <div class="col-lg-12 text-center">
        <% @conversations.each do |c| %>
            <% if c.is_unread?(current_user) %>
                <strong><%= link_to c.subject, conversation_path(c) %> </br></strong>
            <% else %>
                <%= link_to c.subject, conversation_path(c) %> </br>
            <% end %> 
        <% end %>
    </div>
</div>

app/views/conversations/new.html.erb
</br>
</br>
<div class="row">
        <div class="col-lg-12 text-center">
            <h2>Say hi !!! to <%= @reciever.name %></h2>
            <hr class="star-primary">
        </div>
</div>


<div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <%= form_tag conversations_path, method: :post do %>
                                <%= hidden_field_tag :user_id, @reciever.id %>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <%= text_field_tag :subject, nil, class: "form-control", placeholder: "Subject" %>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <%= text_area_tag :body, nil, class: "form-control", placeholder: "Leave a comment" %>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-xs-12">
                                <%= submit_tag "Send Message", class: "btn btn-success btn-lg" %>
                            </div>
                        </div>
                    <% end %>
</div>
            </div>

app/views/conversations/show.html.erb
</br>
</br>
<div class="row">
    <div class="col-lg-12 text-center">
        <h1><%= @conversation.subject %></h1>
        <hr class="star-primary">
    </div>
    <div class="col-lg-12 text-center">
        <% @conversation.receipts_for(current_user).each do |r| %>
        <div>
            <small><%= r.message.sender.name %> : </small>
            <%= r.message.body %>
        </div>
        <% end %>        
    </div>
</div>
<!--Reply-->
</br>
<div class="col-lg-12 text-center">
    <strong>Reply</strong>
    <%= form_tag conversation_messages_path(@conversation), method: :post do %>
        <div><%= text_area_tag :body %></div>
        <%= submit_tag %>
    <% end %>
</div>

app/views/layouts/_nav.html.erb
<!-- Navigation -->
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="/">Home Listing Service</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <% if user_signed_in? %>
                        <li class="page-scroll">
                            <%= link_to "New Post", new_post_path, method: :get, class:"" %>
                        </li>
                        <li class="page-scroll">
                            <%= link_to "Inbox", conversations_path, method: :get, class:"" %>
                        </li>
                        <li class="page-scroll">
                            <%= link_to "Show Listings", posts_path, method: :get, class:"" %>
                        </li>
                        <li class="page-scroll">
                            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"" %>
                        </li>
                        <li class="page-scroll">
                            <%= link_to "Edit Profile", edit_user_registration_path, class:"" %>
                        </li>
                    <% else %>
                        <li class="page-scroll" ><%= link_to "Sign Up", new_user_registration_path, class: "" %></li>
                        <li class="page-scroll" ><%= link_to "Log In", new_user_session_path, class: "" %></li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" 
    crossorigin="anonymous">
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" 
    crossorigin="anonymous"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    
    
    <%= stylesheet_link_tag 'freelancer' %>
    
    <%= javascript_include_tag 'freelancer.min' %>
    
    
  </head>

  <body>

    <%= render 'layouts/nav' %>
    
    <!--TODO change these -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    
    
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" 
    integrity="sha256-/SIrNqv8h6QGKDuNoLGA4iret+kyesCkHGzVUUV0shc=" 
    crossorigin="anonymous"></script>
    
    <%= javascript_include_tag 'jqBootstrapValidation' %>
    
  </body>
</html>

app/views/pages/home.html.erb
<body>
    <!-- Header -->
    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-text">
                        <span class="name"> HomeListing Demo 1 </span>
                        <hr class="star-light">
                        <% if user_signed_in? %>
                           <span class="skills"> Welcome <%= current_user.name %> !! </span>
                        <% end %> 
                        <span class="skills">Your one stop buy and sell</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
</body>

app/views/posts/index.html.erb
<h1> All Posts </h1>

<% @posts.each do |p| %>
    <div>
        <h3><%= link_to p.title, post_path(p.id) %></h3>
        <p><%= p.description %></p>
        Created By: <%= p.user.name %> | <%= time_ago_in_words(p.created_at) %> ago
    </div>
    <%= image_tag p.image.thumb %>
    <%  if current_user == p.user %>
        
    <% else %>
        <span><%= link_to "Send a Message", new_conversation_path(@reciever, :reciever_id => p.user.id) %></span> |
    <% end %>
<% end %>

app/views/posts/new.html.erb
</br>
</br>
<div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Make A new Post</h2>
                    <hr class="star-primary">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <%= form_for(@post) do |h| %>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <%= h.text_field :title, class: "form-control" ,placeholder: "give it a title!!!" %>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <%= h.text_area :description, class: "form-control" ,placeholder: "Compose new Hosting..." %>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <%= h.file_field :image %>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-xs-12">
                                <%= h.submit "post", class: "btn btn-success btn-lg" %>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
</div>

app/views/posts/show.html.erb
<br></br>
<br></br>
<div>
<h1><%= @post.title %> </h1>
<p>
    <%= @post.description %>
</p>
<%= image_tag @post.image %>
<%  if current_user == @post.user %>
    <%= link_to "Delete Post", post_path, method: :delete, class:"" %>
<% else %>
    Contact Seller: <span><%= link_to "Send a Message", new_conversation_path(@reciever, :reciever_id => @post.user.id) %></span>
<%  end %>
</div>